graphql:
  packages:
    - "com.example.graphql"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000

spring:
  jackson:
    timeZone: 'Europe/Warsaw'

    serialization:
      write_dates_as_timestamps: false
      indent_output: true
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true

